### ISSUE TITLE
Layout condicional nao funciona com a versao 2.x

### ISSUE THREAD

**Issue by fabriziofbarros** [vtex/vtex-courses#139]
Se vc usar o "vtex.condition-layout": "2.x", o codigo precisa ser atualizado  e mesmo assim da o seguinte erro
TypeError: Cannot read property 'reduce' of undefined
    at validateConditions (https://fabrizio--appliancetheme.myvtex.com/_v/private/assets/v1/linked/vtex.condition-layout@3.0.1/public/react/ConditionLayoutProduct.js:245:28)
    at ConditionLayout (https://fabrizio--appliancetheme.myvtex.com/_v/private/assets/v1/linked/vtex.condition-layout@3.0.1/public/react/ConditionLayoutProduct.js:58:94)
    at renderWithHooks (https://fabrizio--appliancetheme.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:15246:18)

Somente usando a versao deprecada 1.x funciona

**Comment by christiangarciaacctglobal** [comment]
Good morning, 

in the [conditional layout](https://learn.vtex.com/docs/course-layout-blocks-step09conditional-layout-lang-en) training, it also gives an error when using `"condition.product # retro-mixer"` with `"vtex.condition-layout": "2.x"`
